# Generated by Django 4.2 on 2025-01-25 08:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cajero_Pichincha', '0003_alter_user_options_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(editable=False, max_length=10, unique=True, verbose_name='Número de cuenta'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('corriente', 'Corriente'), ('ahorro', 'Ahorro')], max_length=10, verbose_name='Tipo de cuenta'),
        ),
        migrations.AlterField(
            model_name='account',
            name='funds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='service',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cajero_Pichincha.account', verbose_name='Cuenta'),
        ),
        migrations.AlterField(
            model_name='service',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='service',
            name='bill_number',
            field=models.CharField(max_length=50, verbose_name='Número de factura'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Pagado'),
        ),
        migrations.AlterField(
            model_name='service',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('AGUA', 'Factura de agua'), ('ELECTRICIDAD', 'Factura de Luz')], max_length=20, verbose_name='Tipo de servicio'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Cajero_Pichincha.account', verbose_name='Cuenta'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSITO', 'Depósito'), ('RETIRO', 'Retiro'), ('TRANSFERENCIA', 'Transferencia'), ('PAGO SERVICIOS BASICOS', 'Pago de servicios básicos')], max_length=50, verbose_name='Tipo de transacción'),
        ),
        migrations.AlterField(
            model_name='user',
            name='identification',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Ingrese 10 dígitos numéricos.')], verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Ingrese 10 dígitos numéricos.')], verbose_name='Teléfono'),
        ),
    ]
