# Generated by Django 4.2 on 2025-01-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cajero_Pichincha', '0004_alter_account_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
